version: "3"

services:
  users-db:
    image: mongo
    ports:
      - 27018:27017
    restart: unless-stopped
    volumes:
      - users-data:/data/db

  users-service:
    build:
      context: .
      dockerfile: users/Dockerfile
    environment:
      MONGODB_URI: mongodb://users-db:27017
      TASKS_URI: tasks-service:51075
    volumes:
      - ${PRIVATE_KEY_FILE}:/tmp/signature.pem
      - ${PUBLIC_KEY_FILE}:/tmp/signature.pub
    command: ["--private", "/tmp/signature.pem", "--public", "/tmp/signature.pub", "--port", "8090"]
    ports:
      - 8090:8090
    depends_on:
      - users-db
      - tasks-service

  tasks-db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27019:27017
    volumes:
      - tasks-data:/data/db

  tasks-service:
    build:
      context: .
      dockerfile: tasks/Dockerfile
    environment:
      MONGODB_URI: mongodb://tasks-db:27017
    command: ["--port", "51075"]
    ports:
      - 51075:51075
    depends_on:
      - tasks-db

  stats-db:
    image: yandex/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - 8124:8123
      - 9000:9000
    volumes:
      - stats-data:/data/db

  stats-service:
    build:
      context: .
      dockerfile: stats/Dockerfile
    environment:
      CLICKHOUSE_URI: http://stats-db:8123
    command: ["--port", "51075"]
    ports:
      - 51076:51075
    depends_on:
      - stats-db

volumes:
  users-data:
  tasks-data:
  stats-data:
