openapi: 3.0.0
info:
  title: Task Tracker API
  description: Task Tracker service public API.
  version: 0.1.0
tags:
  - name: Authorization
  - name: Users
  - name: Tasks
paths:
  /auth/signup:
    post:
      tags:
      - Authorization
      summary: Create a new user
      requestBody:
        description: New user's credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreds'
      responses:
        '201':
          description: Successfully signed up a new user. The access token is returned in a cookie named jwt. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: jwt=abcde123456
        '403':
          description: User with speciefied username already exists
  /auth/signin:
    post:
      tags:
        - Authorization
      summary: Authorize user
      requestBody:
        description: User's credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreds'
      responses:
        '200':
          description: Successfully authentificated. The access token is returned in a cookie named `jwt`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: jwt=abcde123456
        '403':
          description: Invalid username or password
  /user/{username}:
    put:
      tags:
        - Users
      summary: Update user data
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData"
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Successfully updated user data
        '404':
          description: User with provided username is not found
        '401':
          description: Access token is missing
        '403':
          description: Access token is invalid
  /task:
    post: 
      tags:
        - Tasks
      summary: Create new task
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                  status:
                    type: string
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A JSON object containing task_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: string
        '401':
          description: Access token is missing
        '403':
          description: Access token is invalid
    get:
      tags:
        - Tasks
      summary: List your tasks by pages
      parameters:
        - name: page_size
          in: query
          schema:
            type: integer
        - name: page_num
          in: query
          schema:
            type: integer
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskArray'
                  
        '401':
          description: Access token is missing
        '403':
          description: Access token is invalid
  /task/{id}:
    get:
      tags:
        - Tasks
      summary: Get task by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Task object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Access token is missing
        '403':
          description: Access token is invalid
        '404':
          description: Task does not exist
    put:
      tags:
        - Tasks
      summary: Update task 
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      security:
        - cookieAuth: []
      responses:
        '200':
          description: OK
        '401':
          description: Access token is missing
        '403':
          description: Access token is invalid
        '404':
          description: Task does not exist
    delete:
      tags:
        - Tasks
      summary: Delete task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - cookieAuth: []
      responses:
        '200':
          description: OK   
        '401':
          description: Access token is missing
        '403':
          description: Access token is invalid
        '404':
          description: Task does not exist

components:
  schemas:
    UserCreds:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: taskkiller
        password: qwerty1234
    UserData:
      type: object
      required: [first_name, last_name, date_birth, phone, email]
      properties:
        first_name:
          type: string
        last_name:
          type: string
        date_birth:
          type: string
          format: date-time
        phone:
          type: string
          format: phone
        email:
          type: string
          format: email
      example:
        firstName: Ivan
        lastName: Ivanov
        dateBirth: 2020-05-11T20:14:14.796Z
        phone: "+791611122233"
        email: iivanov@gmail.com
    Task:
      type: object
      required: [task_id, description, status]
      properties:
        task_id:
          type: string
        description:
          type: string
        status:
          type: string
      example:
        task_id: "abacaba"
        description: "soa hw3"
        satus: "in_progress"
    TaskArray:
      type: array
      items:
        $ref: '#/components/schemas/Task'
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt
